config/routes.rb
Fundit::Application.routes.draw do
    root 'projects#index'
    resources :projects
end

app/models/project.rb
class Project < ActiveRecord::Base

  def pledging_expired?
    pledging_ends_on < Date.today
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to @project
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.save
    redirect_to @project
  end

private

  def project_params
    project_params = params.require(:project).permit(:name, :description, :target_pledge_amount, :pledging_ends_on, :website, :created_at, :updated_at)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def format_pledging_ends_on(project)
    if project.pledging_expired?
      content_tag(:strong, 'All Done!')
    else
      distance_of_time_in_words(Date.today, project.pledging_ends_on) + " remaining"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fundit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_footer.html.erb
<footer>
  <p>
    Welcome to FundIt: the world's premier, fairly useless, fundraising site!
  </p>
</footer>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name, autofocus: true %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description, cols: 40, rows: 7 %>
  </p>
  <p>
    <%= f.label :pledging_ends_on %><br/>
    <%= f.date_select :pledging_ends_on %>
  </p>
  <p>
    <%= f.label :target_pledge_amount %><br/>
    <%= f.number_field :target_pledge_amount %>
  </p>
  <p>
    <%= f.label :website %><br/>
    <%= f.text_field :website %>
  </p>
  <p>
    <%= f.submit %> |
    <%= link_to "Cancel", projects_path %>
  </p>

<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project <%= @project.name %></h1>

<%= render "form" %>
<%= render "footer" %>

app/views/projects/index.html.erb
<h1><%= pluralize(@projects.size, "Project") %></h1>

<%= link_to("Add New Project", new_project_path) %>

<% @projects.each do |project| %>
  <article>
    <header>
      <h2><%= link_to project.name, project_path(project) %></h2>
    </header>
    <p>
      <%= truncate(project.description, length: 150) %>
    </p>
    <table>
      <tr>
        <th>Target Pledge Amount:</th>
        <td><%= number_to_currency(project.target_pledge_amount) %></td>
      </tr>
      <tr>
        <th>Website:</th>
        <td><%= project.website %></td>
      </tr>
      <tr>
        <th>Pledging Ends:</th>
        <td><%= format_pledging_ends_on(project) %></td>
      </tr>
    </table>
  </article>
<% end %>

<%= render "footer" %>

app/views/projects/new.html.erb
<h1>Create Project</h1>

<%= render "form" %>
<%= render "footer" %>

app/views/projects/show.html.erb
<article>
  <header>
    <h2><%= @project.name %></h2>
  </header>
  <h2>Description</h2>
    <p>
      <%= @project.description %>
    </p>
  <h3>Target Pledge Amount:</h3>
    <p>
      <%= number_to_currency(@project.target_pledge_amount) %>
    </p>
  <h3>Website:</h3>
    <p>
      <%= @project.website %>
    </p>
  <h3>Pledging Ends:</h3>
    <p>
      <%= format_pledging_ends_on(@project) %>
    </p>
</article>

<%= link_to "All Projects", projects_path %> |
<%= link_to "Edit", edit_project_path(@project) %>

<%= render "footer" %>